import { jsPDF } from 'jspdf'
import { ThreadsPost } from '@/types/threads-post'
import fs from 'fs'
import path from 'path'

const DOWNLOADS_DIR = path.join(process.cwd(), 'public', 'downloads')

function ensureDownloadsDir() {
  if (!fs.existsSync(DOWNLOADS_DIR)) {
    fs.mkdirSync(DOWNLOADS_DIR, { recursive: true })
  }
}

export async function generatePdf(username: string, posts: ThreadsPost[], sessionId: string): Promise<string> {
  ensureDownloadsDir()

  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  let y = 30

  // Title
  doc.setFontSize(20)
  doc.text(`@${username}`, margin, y)
  y += 10

  doc.setFontSize(10)
  doc.setTextColor(128)
  doc.text(`${posts.length} posts | Generated by Unthread`, margin, y)
  doc.setTextColor(0)
  y += 15

  // Posts
  doc.setFontSize(11)

  for (const post of posts) {
    // Check page break
    if (y > 260) {
      doc.addPage()
      y = 20
    }

    // Date
    doc.setFontSize(9)
    doc.setTextColor(128)
    const dateStr = new Date(post.postedAt).toLocaleDateString('ko-KR', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })
    doc.text(dateStr, margin, y)
    doc.setTextColor(0)
    y += 6

    // Content
    doc.setFontSize(11)
    const lines = doc.splitTextToSize(post.content, maxWidth)
    for (const line of lines) {
      if (y > 275) {
        doc.addPage()
        y = 20
      }
      doc.text(line, margin, y)
      y += 6
    }

    // Separator
    y += 4
    doc.setDrawColor(220)
    doc.line(margin, y, pageWidth - margin, y)
    y += 8
  }

  const filename = `${sessionId}.pdf`
  const filepath = path.join(DOWNLOADS_DIR, filename)
  const buffer = Buffer.from(doc.output('arraybuffer'))
  fs.writeFileSync(filepath, buffer)

  return `/downloads/${filename}`
}
